services:
  recipya:
    container_name: recipya
    image: reaper99/recipya:v1.2.2
    ports:
      - "8078:8078"
    environment:
      - RECIPYA_SERVER_PORT=8078
      - RECIPYA_SERVER_AUTOLOGIN=true
      - RECIPYA_SERVER_IS_PROD=true
    volumes:
      - ${APPDATA_BASE}/recipya:/root/.config/Recipya:Z
    restart: unless-stopped
