services:
  heimdall:
    container_name: heimdall
    image: linuxserver/heimdall:2.6.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${APPDATA_BASE}/heimdall:/config:Z
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    restart: unless-stopped
