services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2024.07.0
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8800:80/tcp"
      - "67:67/udp"
    environment:
      - TZ=Europe/Berlin
      - WEBPASSWORD=${PIHOLE_PASSWORD}
      - FTLCONF_LOCAL_IPV4=0.0.0.0
    volumes:
      - ${APPDATA_BASE}/pihole/etc:/etc/pihole:Z
      - ${APPDATA_BASE}/pihole/dnsmasq:/etc/dnsmasq.d:Z
    restart: unless-stopped
