services:
  metube:
    container_name: metube
    image: ghcr.io/alexta69/metube:2026.01.11
    ports:
      - "8081:8081"
    volumes:
      - ${STORAGE_BASE}/Downloads/MeTube:/downloads:Z
    environment:
      - UID=1000
      - GID=1000
      - DOWNLOAD_DIR=/downloads
    restart: unless-stopped
